# Generated by fusen: do not edit by hand

#' file_explorer
#'
#' @param viewer Where to display the gadget: `"dialog"`,
#'  `"pane"` or `"browser"` (see \code{\link[shiny]{viewer}}).
#'  
#' @return UI gadget
#' @export
#'
#' @examples
#' \dontrun{
#' library(shiny)
#' library(shinyFiles)
#' # shinyFiles::shinyFilesExample()
#' file_explorer()
#' }
file_explorer <- function(viewer = getOption(x = "servers.tools.viewer", default = "dialog")) {
  viewer <- match.arg(viewer, choices = c("dialog", "pane", "browser"))

  if (viewer == "browser") {
    inviewer <- browserViewer(browser = getOption("browser"))
  } else if (viewer == "pane") {
    inviewer <- paneViewer(minHeight = "maximize")
  } else {
    inviewer <- dialogViewer(
      paste(
        "dialog"
      ),
      width = 1100,
      height = 750
    )
  }

  runGadget(
    app = explorer_ui(
      id = "explorer"
    ),
    server = function(input, output, session) {
      explorer_server("explorer")
    },
    viewer = inviewer
  )
}

#' @noRd
explorer_ui <- function(id) {
  ns <- NS(id)
  ui <- fluidPage(
    # theme = bslib::bs_theme(version = 4),
    headerPanel(
      "Selections with shinyFiles",
      "shinyFiles example"
    ),
    sidebarLayout(
      sidebarPanel(
        tags$div(
          shinyFilesButton(ns("file"), "Source File select", "Please select a file", multiple = TRUE, viewtype = "detail"),
          tags$p(),
          tags$p("Select one or multiple files.")
        ),
        tags$div(
          tags$hr(),
          shinyDirButton(ns("directoryfrom"), "Source Folder select", "Please select a folder source"),
          tags$p(),
          tags$p("Select a directory."),
        ),
        tags$div(
          tags$hr(),
          shinyDirButton(ns("directoryto"), "Target Folder select", "Please select a folder target"),
          tags$p(),
          tags$p("Select a directory."),
        ),
        tags$div(
          tags$hr(),
          shinySaveButton(ns("save"), "Target File Create", "Save file as...", 
                          # filetype = list(text = "txt", picture = c("jpeg", "jpg")),
                          viewtype = "detail"),
          tags$p(),
          tags$p('Create a new file path')
        ),
        tags$div(
          tags$hr(),
          shiny::actionButton(ns("savefiletodir"), label = "Save Source files to Target directory"),
          tags$p("Will save sources files listed into directory selected"),
          shiny::actionButton(ns("savefiletofile"), label = "Save Source file to new Target file"),
          tags$p("Will save first source file listed into new file name created"),
          shiny::actionButton(ns("savedirtodir"), label = "Save Source Folder to Target Folder"),
          tags$p("Will save first source folder listed into target folder listed")
        )
      ),
      mainPanel(
        tags$h4("Outputs of selections"),
        tags$p("Source filepaths selected"),
        verbatimTextOutput(ns("filepaths")),
        tags$p("Source dir path selected"),
        verbatimTextOutput(ns("directoryfrompath")),
        tags$p("Target dir path selected"),
        verbatimTextOutput(ns("directorytopath")),
        tags$p("file saved"),
        verbatimTextOutput(ns("savefile"))
      )
    )
  )
}

#' @import shiny
#' @import shinyFiles
#' @noRd
explorer_server <- function(id) {
  moduleServer(
    id = id,
    module = function(input, output, session) {
      ns <- session$ns

      volumes <- c("Current Dir" = getwd(), Home = fs::path_home(), "R Installation" = R.home(), "Temp dir" = tempdir(), getVolumes()())

      # Find file ----
      shinyFileChoose(input, "file", roots = volumes, session = session, restrictions = system.file(package = "base"))

      output$filepaths <- renderPrint({
        if (is.integer(input$file)) {
          cat("No source files have been selected (shinyFileChoose)")
        } else {
          parseFilePaths(volumes, input$file)
        }
      })

      # Find source dir ----
      shinyDirChoose(input, "directoryfrom", roots = volumes, session = session, restrictions = system.file(package = "base"), allowDirCreate = TRUE)

      output$directoryfrompath <- renderPrint({
        if (is.integer(input$directoryfrom)) {
          cat("No directory has been selected (shinyDirChoose)")
        } else {
          parseDirPath(volumes, input$directoryfrom)
        }
      })
      
            # Find target dir ----
      shinyDirChoose(input, "directoryto", roots = volumes, session = session, restrictions = system.file(package = "base"), allowDirCreate = TRUE)

      output$directorytopath <- renderPrint({
        if (is.integer(input$directoryto)) {
          cat("No directory has been selected (shinyDirChoose)")
        } else {
          parseDirPath(volumes, input$directoryto)
        }
      })

      # Save file ----
      shinyFileSave(input, "save", roots = volumes, session = session, restrictions = system.file(package = "base"))

      output$savefile <- renderPrint({
        if (is.integer(input$save)) {
          cat("No file-save path has been set (shinyFileSave)")
        } else {
          parseSavePath(volumes, input$save)
        }
      })
      
      # Save from to ----
      # File to dir
      observeEvent(input$savefiletodir, {
        # browser()
        if (is.integer(input$file)) {
          modalDialog(title = "No files have been selected")
        } else if (is.integer(input$directoryto)) {
          modalDialog(title = "No Target directory has been selected")
        } else {
          files <- parseFilePaths(volumes, input$file)
          dirto <- parseDirPath(volumes, input$directoryto)
          fs::file_copy(files$datapath, dirto, overwrite = TRUE)
          cat("file(s)", files$datapath, "copied into", dirto)
        }
      })
      
      # File to new file
      observeEvent(input$savefiletofile, {
        # browser()
        if (is.integer(input$file)) {
          modalDialog(title = "No files have been selected")
        } else if (is.integer(input$save)) {
          modalDialog(title = "No Target file has been selected")
        } else {
          files <- parseFilePaths(volumes, input$file)
          fileto <- parseSavePath(volumes, input$save)
          fs::file_copy(files$datapath[1], fileto$datapath, overwrite = TRUE)
          cat("file", files$datapath[1], "copied into", fileto$datapath)
        }
      })
      
      # Dir to dir
      observeEvent(input$savedirtodir, {
        # browser()
        if (is.integer(input$directoryfrom)) {
          modalDialog(title = "No source directory have been selected")
        } else if (is.integer(input$directoryto)) {
          modalDialog(title = "No Target directory has been selected")
        } else {
          dirfrom <- parseDirPath(volumes, input$directoryfrom)
          dirto <- parseDirPath(volumes, input$directoryto)
          dirtopath <- file.path(dirto, basename(dirfrom))
          if (!dir.exists(dirtopath)) {
            dir.create(dirtopath)
          }
          fs::dir_copy(dirfrom, dirtopath, overwrite = TRUE)
          cat("folder", dirfrom, "copied into", dirtopath)
        }
      })
    }
  )
}
